#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not handle the case statement's patterns as described below, you may need
#       to use /bin/bash and step 9 to regenerate this script.
#
#   (2) Be sure that your "*_HOME" environment variable points to your JAVA_HOME
#       directory so that it can be used by findJavaFromJavaHome in the script.
#
##############################################################################

set -e

DIRNAME=`dirname "$0"` >/dev/null
APP_BASE_NAME=`basename "$0"` >/dev/null

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn ( ) {
    echo "$*"
} >&2

die ( ) {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    MAX_FD_LIMIT=`ulimit -H -n` 2>/dev/null
    if [ $? -eq 0 ] ; then
        if [ "$MAX_FD" = "maximum" -o "$MAX_FD" = "max" ] ; then
            MAX_FD="$MAX_FD_LIMIT"
        fi
        ulimit -n $MAX_FD
        if [ $? -ne 0 ] ; then
            warn "Could not set maximum file descriptor limit: $MAX_FD"
        fi
    else
        warn "Could not query maximum file descriptor limit: $MAX_FD_LIMIT"
    fi
fi

# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_BASE_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=`cygpath --path --mixed "$APP_HOME"`
    CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`

    JAVACMD=`cygpath --unix "$JAVACMD"`

    # We build the pattern for arguments to be converted via cygpath
    ROOTDIRSRAW=`find -L / -maxdepth 3 -type d -name gradle 2>/dev/null | grep -E "^[a-zA-Z]:/"`
    [ -z "$ROOTDIRSRAW" ] && ROOTDIRSRAW=`find -L / -maxdepth 3 -type d -name gradle 2>/dev/null`
    for dir in $ROOTDIRSRAW ; do
        ROOTDIRS="$ROOTDIRS$dir/;"
    done
    IFS=$';\n'
    for dir in $ROOTDIRS ; do
        if [ -d "$dir" ] ; then
            ROOTDIRS_SAFE=`echo "$dir" | sed -s 's/[\/\\]/\\\\/g'`
            CLASSPATH="$CLASSPATH;$ROOTDIRS_SAFE/gradle/wrapper/gradle-wrapper.jar"
        fi
    done
    IFS=" "
    # remove $lang chars from the beginning of MAVEN_PROJECTBASEDIR before passing it to java
    from="${MAVEN_PROJECTBASEDIR//[/\\}"
    MAVEN_PROJECTBASEDIR=`cygpath --path --windows "$from"`
fi

# Escape application home to make it safe to pass as argument to Java
APP_HOME_SAFE=`cygpath --path --absolute "$APP_HOME" 2>/dev/null || echo "$APP_HOME"`
CLASSPATH=`cygpath --path --absolute "$CLASSPATH" 2>/dev/null || echo "$CLASSPATH"`

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell commands we have to avoid doing word splitting on those fragments
#     which would be incorrect.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        "-Dorg.gradle.launcher.bootstrap.name=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.launcher.bootstrap.GradleWrapperMain \
        "$@"

# Stop when "xargs" should not be used (when
# using timdex.exe).

if [ "$1" = "-Xrs" ] ; then
    shift
fi

exec "$JAVACMD" "$@"
